//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gag.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gag.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a .
        /// </summary>
        public static string AdPrefix {
            get {
                return ResourceManager.GetString("AdPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  generated gallery.
        /// </summary>
        public static string AdSuffix {
            get {
                return ResourceManager.GetString("AdSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mail adress(es).
        /// </summary>
        public static string BadMail {
            get {
                return ResourceManager.GetString("BadMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find any occurence of the &lt;span class = &quot;pic&quot;&gt; in the template. Please check it&apos;s present..
        /// </summary>
        public static string BadTemplate {
            get {
                return ResourceManager.GetString("BadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        /// </summary>
        public static string BadURL {
            get {
                return ResourceManager.GetString("BadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory isn&apos;t void. All of it&apos;s content will be deleted.
        /// </summary>
        public static string FullOutDir {
            get {
                return ResourceManager.GetString("FullOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login: .
        /// </summary>
        public static string htLogin {
            get {
                return ResourceManager.GetString("htLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: .
        /// </summary>
        public static string htPassword {
            get {
                return ResourceManager.GetString("htPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image display courtesy of .
        /// </summary>
        public static string LightBox {
            get {
                return ResourceManager.GetString("LightBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Zip File, might be long, please wait....
        /// </summary>
        public static string MakingZip {
            get {
                return ResourceManager.GetString("MakingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser seems not to support this video. You may try &lt;a href=&quot;www.getfirefox.com&quot;&gt;Firefox&lt;/a&gt;.
        /// </summary>
        public static string NoVideoTagSupport {
            get {
                return ResourceManager.GetString("NoVideoTagSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing {0}  ({2}/3): {1}% remaining {3}s.
        /// </summary>
        public static string ProcessVideo {
            get {
                return ResourceManager.GetString("ProcessVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 - Generate the web pictures.
        /// </summary>
        public static string ProgressBarStep1Title {
            get {
                return ResourceManager.GetString("ProgressBarStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape 1 - Processing video %v%, it might take some time..
        /// </summary>
        public static string ProgressBarStep1VideoTitle {
            get {
                return ResourceManager.GetString("ProgressBarStep1VideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 - Push the files on the FTP server.
        /// </summary>
        public static string ProgressBarStep2Title {
            get {
                return ResourceManager.GetString("ProgressBarStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original sized pictures archive (.zip).
        /// </summary>
        public static string ZipArchive {
            get {
                return ResourceManager.GetString("ZipArchive", resourceCulture);
            }
        }
    }
}
